export const SET_SELECTED_BUILDING_NUMBER = 'SET_SELECTED_BUILDING_NUMBER';
export const UPDATE_SELECTED_BUILDIING_TYPE = 'UPDATE_SELECTED_BUILDIING_TYPE';
export const UPDATE_SELECTED_ROOF_TYPE = "UPDATE_SELECTED_ROOF_TYPE";
export const UPDATE_SELECTED_ROOF_ANGLE = "UPDATE_SELECTED_ROOF_ANGLE";
export const UPDATE_SELECTED_ROOF_PITCH = "UPDATE_SELECTED_ROOF_PITCH";
export const UPDATE_SELECTED_RIDGE_DIRECTION = "UPDATE_SELECTED_RIDGE_DIRECTION";