export const SET_ADDRESS_BY_ID = "SET_ADDRESS_BY_ID";
export const SET_ADDRESS = "SET_ADDRESS";

export const SEARCH_ADDRESS = "SEARCH_ADDRESS";
export const SEARCH_ADDRESS_SUCCESS = "SEARCH_ADDRESS_SUCCESS";
export const SEARCH_ADDRESS_FAILURE = "SEARCH_ADDRESS_FAILURE";

export const CLEAR_ADDRESS = "CLEAR_ADDRESS";
