export const ADD_ROOF = "ADD_ROOF";
export const REMOVE_ROOF = "REMOVE_ROOF";
export const UPDATE_ROOF_DETAILS = "UPDATE_ROOF_DETAILS";
export const UPDATE_ROOF_SPACE = "UPDATE_ROOF_SPACE";
export const SET_SELECTED_ROOF = "SET_SELECTED_ROOF";
export const SET_EDIT_ROOF_OPEN = "SET_EDIT_ROOF_OPEN";
export const SET_ROOF_MOBILE_MENU_OPEN = "SET_ROOF_MOBILE_MENU_OPEN";
export const ADD_RESULT_ROOF = "ADD_RESULT_ROOF";
export const REMOVE_RESULT_ROOF = "REMOVE_RESULT_ROOF";
export const CLEAN_ROOFS = "CLEAN_ROOFS";
export const CREATE_ROOF_SQUARE = "CREATE_ROOF_SQUARE";

/**
 * <--- harrypotter --->
 */

//...builder component
export const SET_HIGHEST_BUILDING_HEIGHT = "SET_HIGHEST_BUILDING_HEIGHT";
export const CREATE_HIGHEST_BUILDING_HEIGHT = "CREATE_HIGHEST_BUILDING_HEIGHT";
export const SET_SELECTED_SOLAR_OBJECT = "SET_SELECTED_SOLAR_OBJECT";
export const HANDLE_ORBIT_CAMERA = "HANDLE_ORBIT_CAMERA";
export const SET_CONTROL_PANEL_CONTENT = "SET_CONTROL_PANEL_CONTENT";
export const SET_ROOFS_DATA = "SET_ROOFS_DATA";
export const UPDATE_ROOFS_DATA = "UPDATE_ROOFS_DATA";
export const SET_CURRENT_BUILDING_ID = "SET_CURRENT_BUILDING_ID";
export const SET_ADD_SOLAR_PANEL_STATE = "SET_ADD_SOLAR_PANEL_STATE";
export const DOM_RENDER_STATE = "DOM_RENDER_STATE";

export const GOOGLE_MAP_IMAGE_URL = "GOOGLE_MAP_IMAGE_URL";
export const MAP_TEXTURE_SHOW_STATE = "MAP_TEXTURE_SHOW_STATE";
export const SET_SOLAR_PANEL_COUNT_INFO = "SET_SOLAR_PANEL_COUNT_INFO";
export const UPDATE_SOLAR_PANEL_COUNT_INFO = "UPDATE_SOLAR_PANEL_COUNT_INFO";

export const SET_SHOW_MODAL_STATE = "SET_SHOW_MODAL_STATE";
export const SET_RESULT_CAPTURE_IMAGE = "SET_RESULT_CAPTURE_IMAGE";
export const SET_SHOW_ROOF_OPTION = "SET_SHOW_ROOF_OPTION";
//---------------------
