export const ON_POLYGON_COMPLETE = "ON_POLYGON_COMPLETE";
export const SET_DRAWING_MODE = "SET_DRAWING_MODE";
export const SET_MAP_CENTER = "SET_MAP_CENTER";
export const GET_MAP_CENTER = "GET_MAP_CENTER";
export const SET_PLACING_OBSTACLE = "GET_MAP_CENTER";
