export const ADD_OBSTACLE = "ADD_OBSTACLE";
export const REMOVE_OBSTACLE = "REMOVE_OBSTACLE";
export const UPDATE_OBSTACLE_DETAILS = "UPDATE_OBSTACLE_DETAILS";
export const UPDATE_OBSTACLE_SPACE = "UPDATE_OBSTACLE_SPACE";
export const SET_SELECTED_OBSTACLE = "SET_SELECTED_OBSTACLE";
export const SET_EDIT_OBSTACLE_OPEN = "SET_EDIT_OBSTACLE_OPEN";
export const SET_OBSTACLE_MOBILE_MENU_OPEN = "SET_OBSTACLE_MOBILE_MENU_OPEN";
export const ADD_RESULT_OBSTACLE = "ADD_RESULT_OBSTACLE";
export const REMOVE_RESULT_OBSTACLE = "REMOVE_RESULT_OBSTACLE";
export const CLEAN_OBSTACLES = "CLEAN_OBSTACLES";
export const CREATE_OBSTACLE_SQUARE = "CREATE_OBSTACLE_SQUARE";

/**
 * <--- harrypotter --->
 */

//...builder component
export const SET_HIGHEST_BUILDING_HEIGHT = "SET_HIGHEST_BUILDING_HEIGHT";
export const CREATE_HIGHEST_BUILDING_HEIGHT = "CREATE_HIGHEST_BUILDING_HEIGHT";
export const SET_SELECTED_SOLAR_OBJECT = "SET_SELECTED_SOLAR_OBJECT";
export const GET_SOLAR_PANEL_COUNT = "GET_SOLAR_PANEL_COUNT";
export const HANDLE_ORBIT_CAMERA = "HANDLE_ORBIT_CAMERA";
export const SET_OBSTACLES_DATA = "SET_OBSTACLES_DATA";
export const UPDATE_OBSTACLES_DATA = "UPDATE_OBSTACLES_DATA";
export const SET_CURRENT_OBSTACLE_ID = "SET_CURRENT_OBSTACLE_ID";
export const SET_SELECTED_OBSTACLE_OBJECT = "SET_SELECTED_OBSTACLE_OBJECT";
//---------------------
